services:
  app:
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    volumes:
      - ./dist/src/data:/app/dist/src/data
    user: "1000:1000"
    networks:
      - traefik-public
    labels:
      traefik.enable: "true"
      traefik.http.routers.ewt-foundation.rule: "Host(`ewt-foundation.homelab-kaleici.space`)"
      traefik.http.routers.ewt-foundation.entrypoints: "websecure"
      traefik.http.services.ewt-foundation.loadbalancer.server.port: "3000"
      traefik.http.routers.ewt-foundation.tls: "true"
      traefik.http.routers.ewt-foundation.tls.certresolver: "cloudflare"
      traefik.http.middlewares.ewt-foundation-headers.headers.sslredirect: "true"
networks:
  traefik-public:
    external: true
