services:
  app:
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src/data:/app/src/data
    user: "1000:1000"
    entrypoint: >
      /bin/sh -c "
        mkdir -p /app/src/data &&
        chown -R appuser:appgroup /app/src/data &&
        chmod 755 /app/src/data &&
        node dist/index.js
      "
    labels:
      traefik.enable: "true"
      traefik.http.routers.ewt-foundation.rule: "Host(`ewt-foundation.homelab-kaleici.space`)"
      traefik.http.routers.ewt-foundation.entrypoints: "websecure"
      traefik.http.services.ewt-foundation.loadbalancer.server.port: "3000"
      traefik.http.routers.ewt-foundation.tls: "true"
      traefik.http.routers.ewt-foundation.tls.certresolver: "cloudflare"
      traefik.http.middlewares.ewt-foundation-headers.headers.sslredirect: "true"
