services:
  app:
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
